Repository PrestaShop/prestashop-shop-creator, pull requests merged in 2022-11, with the labels that each got.

#16 Fix faker image provider error
  composer.json
  composer.lock
  patches/faker-provider-image.patch
Labels: QA :heavy_check_mark:

#15 Fix error when adress country is ES_es and dni is mandatory
  src/Model/Address.yml
Labels: bug, QA ✔️

#30 Upgrade phpunit and deps, fix composer
  composer.lock
Labels: QA ✔️

#24 Avoid infinite loop when we can't find a matching relation with conditions
  src/Generator/EntityGenerator.php
Labels: QA ✔️
